### ISSUE TITLE
alpine linux as base image

### ISSUE THREAD

**Issue by lramage94** [mcandre/docker-ecl#3]
Hello,
I have packaged and am maintaining ecl in alpine linux upstream.

- [Docker Hub: Alpine Linux Edge](https://hub.docker.com/r/library/alpine/tags/edge/)
- [Alpine Linux Packages: community/ecl](https://pkgs.alpinelinux.org/packages?name=ecl&branch=edge&repo=community)

**Comment by mcandre** [comment]
@lramage94 That's awesome! Pull requests appreciated if you'd like to make the tweak to the Dockerfile in this project to transition from `apt-get install ecl` to `apk add -U ecl`.
